from sklearn.datasets import load_wine

print("W pierwszej kolejnosci ladujemy dane:")
wine_data = load_wine()
print("Analizujemy zaladowane dane:")
print("")
print("-.-.-.-.-.-.-.-.-.-.-.-.-.-.")
print("")
print("Opis zaladowanego zbioru:")
print(wine_data.DESCR)
print("")
print("-.-.-.-.-.-.-.-.-.-.-.-.-.-.")
print("")
print("Cechy zaladowanego zbioru:")
print(wine_data.feature_names)
print("")
print("-.-.-.-.-.-.-.-.-.-.-.-.-.-.")
print("")
print("Nazwy klas zaladowanego zbioru:")
print(wine_data.target_names)
print("")
print("-.-.-.-.-.-.-.-.-.-.-.-.-.-.")
print("")
print("Wyswietlanie probek w zaladowanym zbiorze:")
print(wine_data.target)
